resources:
  repositories:
  # The name used to reference this repository in the checkout step
  - repository: KangsBashCalcRepo 
    type: github
    endpoint: LoganGitHub
    name: testlogmsci/bashCalc
# The name used to reference this repository in the checkout step
  - repository: KangsWindowsBatchRepo
    type: github
    endpoint: LoganGitHub
    name: testlogmsci/winBatch

trigger:
- master

stages:
#First Stage on Ubuntu
- stage: UbuntuQAEnvCheck
  jobs:
  - job: InlineScripts

    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
    - checkout: none
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

#Second Stage on Ubuntu Prod
- stage: UbuntuProdEnvCheck
  dependsOn: UbuntuQAEnvCheck
  condition: succeeded()
  jobs:
  - job: ExternalScripts
    pool:
      vmImage: 'ubuntu-latest'
     # these variables only available in ExternalScripts job
    variables:
      FIRST: 100
      SECOND: 20
      OPERATION: 4

    steps:
      - checkout: KangsBashCalcRepo
      - task: Bash@3
        displayName: 'install bc'
        inputs:
          targetType: 'inline'
          script: |
            # Write your commands here

            echo 'installation starts'
            sudo apt-get install bc
            echo 'installation ends'

      - task: Bash@3
        displayName: 'run calc'
        inputs:
          filePath: 'calc.sh'